POST http://localhost:7071/api/v1/plants/

{
  "plantType": "Bush",
  "name": "TestBush",
  "maxHeight": 200,
  "price": 169.5
}

###

GET http://localhost:7071/api/v1/plants/

###

DELETE http://localhost:7071/api/v1/plants/2

